FROM node:18.16-alpine3.17

RUN apk add openssl
RUN apk add bash

# Wait-for-it alpine compatible version
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /opt/bin/
RUN chmod +x /opt/bin/wait-for-it.sh

WORKDIR /app
COPY . /app

EXPOSE 3000

CMD ./docker/service/setup.sh
